CREATE TABLE common_rail_12_core (
    id INT(11) NOT NULL AUTO_INCREMENT,

    line_id VARCHAR(10) DEFAULT NULL,
    pg VARCHAR(10) DEFAULT NULL,
    line_name VARCHAR(50) DEFAULT NULL,
    name_product VARCHAR(100) DEFAULT NULL,
    target VARCHAR(50) DEFAULT NULL,
    actual VARCHAR(50) DEFAULT NULL,
    loading_time VARCHAR(50) DEFAULT NULL,
    efficiency VARCHAR(50) DEFAULT NULL,
    delay VARCHAR(50) DEFAULT NULL,
    cycle_time VARCHAR(50) DEFAULT NULL,
    status VARCHAR(50) DEFAULT NULL,
    time_trouble VARCHAR(50) DEFAULT NULL,
    time_trouble_quality VARCHAR(50) DEFAULT NULL,
    andon VARCHAR(50) DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    manpower VARCHAR(50) DEFAULT NULL,
    manpower_help VARCHAR(50) DEFAULT NULL,
    loading_time_manpower_help VARCHAR(50) DEFAULT NULL,
    machine_fault_preq VARCHAR(50) DEFAULT NULL,
    machine_fault_duration VARCHAR(50) DEFAULT NULL,
    quality_check VARCHAR(50) DEFAULT NULL,
    another VARCHAR(50) DEFAULT NULL,
    kaizen VARCHAR(50) DEFAULT NULL,
    five_s VARCHAR(50) DEFAULT NULL,
    manhour_in_line VARCHAR(50) DEFAULT NULL,
    manhour_helper VARCHAR(50) DEFAULT NULL,
    manhour_five_s VARCHAR(50) DEFAULT NULL,
    total_manhour VARCHAR(50) DEFAULT NULL,
    manhour_man_minutes_per_pcs VARCHAR(50) DEFAULT NULL,
    PE VARCHAR(50) DEFAULT NULL,
    bottle_neck_process VARCHAR(50) DEFAULT NULL,
    bottle_neck_process_duration VARCHAR(50) DEFAULT NULL,
    bottle_neck_mct VARCHAR(50) DEFAULT NULL,
    bottle_neck_mct_duration VARCHAR(50) DEFAULT NULL,
    setup_manpower VARCHAR(50) DEFAULT NULL,
    setup_ct VARCHAR(50) DEFAULT NULL,
    dangae VARCHAR(50) DEFAULT NULL,
    delta_time VARCHAR(100) DEFAULT NULL,
    year INT(4) DEFAULT NULL,
    month INT(2) DEFAULT NULL,
    day VARCHAR(20) DEFAULT NULL,
    shift VARCHAR(10) DEFAULT NULL,
    time_only TIME DEFAULT NULL,
    loading_time_server VARCHAR(255) DEFAULT NULL,
    total_break DECIMAL(5,2) DEFAULT NULL,

    PRIMARY KEY (id),
    INDEX (line_id),
    INDEX (status),
    INDEX (created_at),
    INDEX (shift)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
