-- File: database_setup.sql
CREATE TABLE IF NOT EXISTS common_rail_3_manhour (
    idPrimary INT AUTO_INCREMENT PRIMARY KEY,
    cycle_number INT,
    line_id VARCHAR(10),
    pg VARCHAR(50),
    line_name VARCHAR(255),
    product_name VARCHAR(255) NOT NULL,
    target INT DEFAULT 0,
    actual INT DEFAULT 0,
    loading_time DECIMAL(10,2) DEFAULT 0.00,
    efficiency DECIMAL(5,2) DEFAULT 0.00,
    delay DECIMAL(10,2) DEFAULT 0.00,
    cycle_time DECIMAL(10,2) DEFAULT 0.00,
    status VARCHAR(50),
    time_trouble DECIMAL(10,2) DEFAULT 0.00,
    time_trouble_quality DECIMAL(10,2) DEFAULT 0.00,
    andon VARCHAR(50),
    delta_time VARCHAR(255),
    shift VARCHAR(50),
    start_time DATETIME NOT NULL,
    end_time DATETIME NOT NULL,
    start_actual INT DEFAULT 0,
    end_actual INT DEFAULT 0,
    total_produced INT DEFAULT 0,
    record_count INT DEFAULT 0,
    year INT,
    month INT,
    day INT,
    time_only TIME,
    loading_time_server VARCHAR(255),
    total_break DECIMAL(10,2) DEFAULT 0.00,
    manpower DECIMAL(10,2) DEFAULT 0.00,
    manpower_help DECIMAL(10,2) DEFAULT 0.00,
    loading_time_manpower_help DECIMAL(10,2) DEFAULT 0.00,
    machine_fault_preq INT DEFAULT 0,
    machine_fault_duration DECIMAL(10,2) DEFAULT 0.00,
    quality_check DECIMAL(10,2) DEFAULT 0.00,
    another DECIMAL(10,2) DEFAULT 0.00,
    kaizen DECIMAL(10,2) DEFAULT 10.00,
    five_s DECIMAL(10,2) DEFAULT 10.00,
    manhour_in_line DECIMAL(10,2) DEFAULT 0.00,
    manhour_helper DECIMAL(10,2) DEFAULT 0.00,
    manhour_five_s DECIMAL(10,2) DEFAULT 0.00,
    total_manhour DECIMAL(10,2) DEFAULT 0.00,
    manhour_man_minutes_per_pcs DECIMAL(10,2) DEFAULT 0.00,
    PE DECIMAL(5,2) DEFAULT 0.00,
    bottle_neck_process VARCHAR(255),
    bottle_neck_process_duration DECIMAL(10,2) DEFAULT 0.00,
    bottle_neck_mct VARCHAR(255),
    bottle_neck_mct_duration DECIMAL(10,2) DEFAULT 0.00,
    setup_manpower DECIMAL(10,2) DEFAULT 0.00,
    setup_ct DECIMAL(10,2) DEFAULT 0.00,
    dangae DECIMAL(10,2) DEFAULT 0.00,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
