CREATE TABLE tb_cr1_manhour (
    id_uuid CHAR(36) NOT NULL DEFAULT (UUID()),
    line_id VARCHAR(10) NULL,
    pg VARCHAR(10) NULL,
    line_name VARCHAR(50) NULL,
    name_product VARCHAR(100) NULL,
    target VARCHAR(50) NULL,
    actual VARCHAR(50) NULL,
    loading_time VARCHAR(50) NULL,
    efficiency VARCHAR(50) NULL,
    delay VARCHAR(50) NULL,
    cycle_time VARCHAR(50) NULL,
    status VARCHAR(50) NULL,
    time_trouble VARCHAR(50) NULL,
    time_trouble_quality VARCHAR(50) NULL,
    andon VARCHAR(50) NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    manpower VARCHAR(50) NULL,
    manpower_help VARCHAR(50) NULL,
    loading_time_manpower_help VARCHAR(50) NULL,
    machine_fault_preq VARCHAR(50) NULL,
    machine_fault_duration VARCHAR(50) NULL,
    quality_check VARCHAR(50) NULL,
    another VARCHAR(50) NULL,
    kaizen VARCHAR(50) NULL,
    five_s VARCHAR(50) NULL,
    manhour_in_line VARCHAR(50) NULL,
    manhour_helper VARCHAR(50) NULL,
    manhour_five_s VARCHAR(50) NULL,
    total_manhour VARCHAR(50) NULL,
    manhour_man_minutes_per_pcs VARCHAR(50) NULL,
    PE VARCHAR(50) NULL,
    bottle_neck_process VARCHAR(50) NULL,
    bottle_neck_process_duration VARCHAR(50) NULL,
    bottle_neck_mct VARCHAR(50) NULL,
    bottle_neck_mct_duration VARCHAR(50) NULL,
    setup_manpower VARCHAR(50) NULL,
    setup_ct VARCHAR(50) NULL,
    dangae VARCHAR(50) NULL,
    delta_time VARCHAR(100) NULL,
    year INT(4) NULL,
    month INT(2) NULL,
    day VARCHAR(20) NULL,
    shift VARCHAR(10) NULL,
    time_only TIME NULL,
    loading_time_start CHAR(50) NULL,
    loading_time_stop CHAR(50) NULL,
    loading_time_server VARCHAR(255) NULL,
    total_break DECIMAL(5,2) NULL,

    PRIMARY KEY (id_uuid),
    INDEX idx_line_id (line_id),
    INDEX idx_status (status),
    INDEX idx_created_at (created_at),
    INDEX idx_shift (shift)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;

-- File: database_setup.sql
CREATE TABLE IF NOT EXISTS common_rail_3_manhour (
    idPrimary INT AUTO_INCREMENT PRIMARY KEY,
    cycle_number INT,
    line_id VARCHAR(10),
    pg VARCHAR(50),
    line_name VARCHAR(255),
    product_name VARCHAR(255) NOT NULL,
    target INT DEFAULT 0,
    actual INT DEFAULT 0,
    loading_time DECIMAL(10,2) DEFAULT 0.00,
    efficiency DECIMAL(5,2) DEFAULT 0.00,
    delay DECIMAL(10,2) DEFAULT 0.00,
    cycle_time DECIMAL(10,2) DEFAULT 0.00,
    status VARCHAR(50),
    time_trouble DECIMAL(10,2) DEFAULT 0.00,
    time_trouble_quality DECIMAL(10,2) DEFAULT 0.00,
    andon VARCHAR(50),
    delta_time VARCHAR(255),
    shift VARCHAR(50),
    start_time DATETIME NOT NULL,
    end_time DATETIME NOT NULL,
    start_actual INT DEFAULT 0,
    end_actual INT DEFAULT 0,
    total_produced INT DEFAULT 0,
    record_count INT DEFAULT 0,
    year INT,
    month INT,
    day INT,
    time_only TIME,
    loading_time_server VARCHAR(255),
    total_break DECIMAL(10,2) DEFAULT 0.00,
    manpower DECIMAL(10,2) DEFAULT 0.00,
    manpower_help DECIMAL(10,2) DEFAULT 0.00,
    loading_time_manpower_help DECIMAL(10,2) DEFAULT 0.00,
    machine_fault_preq INT DEFAULT 0,
    machine_fault_duration DECIMAL(10,2) DEFAULT 0.00,
    quality_check DECIMAL(10,2) DEFAULT 0.00,
    another DECIMAL(10,2) DEFAULT 0.00,
    kaizen DECIMAL(10,2) DEFAULT 10.00,
    five_s DECIMAL(10,2) DEFAULT 10.00,
    manhour_in_line DECIMAL(10,2) DEFAULT 0.00,
    manhour_helper DECIMAL(10,2) DEFAULT 0.00,
    manhour_five_s DECIMAL(10,2) DEFAULT 0.00,
    total_manhour DECIMAL(10,2) DEFAULT 0.00,
    manhour_man_minutes_per_pcs DECIMAL(10,2) DEFAULT 0.00,
    PE DECIMAL(5,2) DEFAULT 0.00,
    bottle_neck_process VARCHAR(255),
    bottle_neck_process_duration DECIMAL(10,2) DEFAULT 0.00,
    bottle_neck_mct VARCHAR(255),
    bottle_neck_mct_duration DECIMAL(10,2) DEFAULT 0.00,
    setup_manpower DECIMAL(10,2) DEFAULT 0.00,
    setup_ct DECIMAL(10,2) DEFAULT 0.00,
    dangae DECIMAL(10,2) DEFAULT 0.00,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

