CREATE TABLE tb_cr1_manhour (
    id_uuid CHAR(36) NOT NULL DEFAULT (UUID()),
    line_id VARCHAR(10) NULL,
    pg VARCHAR(10) NULL,
    line_name VARCHAR(50) NULL,
    name_product VARCHAR(100) NULL,
    target VARCHAR(50) NULL,
    actual VARCHAR(50) NULL,
    loading_time VARCHAR(50) NULL,
    efficiency VARCHAR(50) NULL,
    delay VARCHAR(50) NULL,
    cycle_time VARCHAR(50) NULL,
    status VARCHAR(50) NULL,
    time_trouble VARCHAR(50) NULL,
    time_trouble_quality VARCHAR(50) NULL,
    andon VARCHAR(50) NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    manpower VARCHAR(50) NULL,
    manpower_help VARCHAR(50) NULL,
    loading_time_manpower_help VARCHAR(50) NULL,
    machine_fault_preq VARCHAR(50) NULL,
    machine_fault_duration VARCHAR(50) NULL,
    quality_check VARCHAR(50) NULL,
    another VARCHAR(50) NULL,
    kaizen VARCHAR(50) NULL,
    five_s VARCHAR(50) NULL,
    manhour_in_line VARCHAR(50) NULL,
    manhour_helper VARCHAR(50) NULL,
    manhour_five_s VARCHAR(50) NULL,
    total_manhour VARCHAR(50) NULL,
    manhour_man_minutes_per_pcs VARCHAR(50) NULL,
    PE VARCHAR(50) NULL,
    bottle_neck_process VARCHAR(50) NULL,
    bottle_neck_process_duration VARCHAR(50) NULL,
    bottle_neck_mct VARCHAR(50) NULL,
    bottle_neck_mct_duration VARCHAR(50) NULL,
    setup_manpower VARCHAR(50) NULL,
    setup_ct VARCHAR(50) NULL,
    dangae VARCHAR(50) NULL,
    delta_time VARCHAR(100) NULL,
    year INT(4) NULL,
    month INT(2) NULL,
    day VARCHAR(20) NULL,
    shift VARCHAR(10) NULL,
    time_only TIME NULL,
    loading_time_start CHAR(50) NULL,
    loading_time_stop CHAR(50) NULL,
    loading_time_server VARCHAR(255) NULL,
    total_break DECIMAL(5,2) NULL,

    PRIMARY KEY (id_uuid),
    INDEX idx_line_id (line_id),
    INDEX idx_status (status),
    INDEX idx_created_at (created_at),
    INDEX idx_shift (shift)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;





