[
    {
        "id": "hivemq-broker",
        "type": "mqtt-broker",
        "name": "HiveMQ Public",
        "broker": "broker.hivemq.com",
        "port": "1883",
        "clientid": "",
        "autoConnect": true,
        "usetls": false,
        "protocolVersion": "4",
        "keepalive": "60",
        "cleansession": true,
        "birthTopic": "",
        "birthQos": "0",
        "birthRetain": "false",
        "birthPayload": "",
        "closeTopic": "",
        "closeQos": "0",
        "closeRetain": "false",
        "closePayload": "",
        "willTopic": "",
        "willQos": "0",
        "willRetain": "false",
        "willPayload": ""
    },
    {
        "id": "mqtt-in",
        "type": "mqtt in",
        "z": "flow-1",
        "name": "Receive Messages",
        "topic": "chat/room/public",
        "qos": "1",
        "datatype": "auto",
        "broker": "hivemq-broker",
        "nl": false,
        "rap": true,
        "rh": 0,
        "inputs": 0,
        "x": 250,
        "y": 200,
        "wires": [
            ["process-message", "debug-message"]
        ]
    },
    {
        "id": "mqtt-out",
        "type": "mqtt out",
        "z": "flow-1",
        "name": "Send Message",
        "topic": "chat/room/public",
        "qos": "1",
        "retain": false,
        "respTopic": "",
        "contentType": "",
        "userProps": "",
        "correl": "",
        "expiry": "",
        "broker": "hivemq-broker",
        "x": 750,
        "y": 120,
        "wires": []
    },
    {
        "id": "process-message",
        "type": "function",
        "z": "flow-1",
        "name": "Format Chat Message",
        "func": "// Simpan username (bisa dari input atau tetap)\nconst username = context.get('username') || 'User' + Math.floor(Math.random() * 1000);\n\n// Jika ini pesan dari pengguna lain\nif (msg.payload && typeof msg.payload === 'object') {\n    msg.payload = `${msg.payload.user}: ${msg.payload.message} \\n`;\n    msg.topic = \"chat_display\";\n} else if (msg.payload && typeof msg.payload === 'string') {\n    // Jika pesan adalah string langsung\n    msg.payload = `Unknown: ${msg.payload}\\n`;\n    msg.topic = \"chat_display\";\n}\n\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 450,
        "y": 200,
        "wires": [
            ["chat-history", "ui-chat-display"]
        ]
    },
    {
        "id": "send-message-function",
        "type": "function",
        "z": "flow-1",
        "name": "Prepare Message",
        "func": "// Ambil username\nlet username = context.get('username');\nif (!username) {\n    username = 'User' + Math.floor(Math.random() * 1000);\n    context.set('username', username);\n    node.status({fill:\"green\",shape:\"dot\",text:username});\n}\n\n// Format pesan\nconst message = {\n    user: username,\n    message: msg.payload,\n    timestamp: new Date().toISOString(),\n    clientId: context.get('clientId') || 'node-red-client'\n};\n\nmsg.payload = message;\nmsg.topic = \"chat/room/public\";\n\n// Juga tampilkan di UI lokal\nconst localMsg = {\n    payload: `${username}: ${msg.payload.message}\\n`,\n    topic: \"chat_display\"\n};\n\nreturn [[msg, localMsg]];",
        "outputs": 2,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 500,
        "y": 120,
        "wires": [
            ["mqtt-out"],
            ["chat-history", "ui-chat-display"]
        ]
    },
    {
        "id": "set-username",
        "type": "function",
        "z": "flow-1",
        "name": "Set Username",
        "func": "// Set username dari input\nif (msg.payload && msg.payload.trim() !== '') {\n    context.set('username', msg.payload.trim());\n    node.status({fill:\"green\",shape:\"dot\",text:msg.payload.trim()});\n    \n    // Kirim notifikasi\n    const notification = {\n        payload: `\\n=== Anda bergabung sebagai: ${msg.payload.trim()} ===\\n`,\n        topic: \"chat_display\"\n    };\n    \n    return notification;\n}\nreturn null;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 450,
        "y": 280,
        "wires": [
            ["chat-history", "ui-chat-display"]
        ]
    },
    {
        "id": "clear-chat",
        "type": "function",
        "z": "flow-1",
        "name": "Clear Chat",
        "func": "msg.payload = \"\\n=== Chat cleared ===\\n\";\nmsg.topic = \"chat_display\";\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 450,
        "y": 360,
        "wires": [
            ["chat-history", "ui-chat-display"]
        ]
    },
    {
        "id": "chat-history",
        "type": "file",
        "z": "flow-1",
        "name": "Chat History",
        "filename": "chat_history.txt",
        "appendNewline": true,
        "createDir": false,
        "overwriteFile": "false",
        "encoding": "utf8",
        "x": 650,
        "y": 200,
        "wires": [
            []
        ]
    },
    {
        "id": "debug-message",
        "type": "debug",
        "z": "flow-1",
        "name": "Debug Raw MQTT",
        "active": false,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "payload",
        "targetType": "msg",
        "statusVal": "",
        "statusType": "auto",
        "x": 450,
        "y": 160,
        "wires": []
    },
    {
        "id": "ui-username",
        "type": "ui_text_input",
        "z": "flow-1",
        "name": "Username Input",
        "label": "Username Anda",
        "tooltip": "",
        "group": "chat-group",
        "order": 1,
        "width": 6,
        "height": 1,
        "passthru": false,
        "mode": "text",
        "delay": 300,
        "topic": "set_username",
        "x": 250,
        "y": 280,
        "wires": [
            ["set-username"]
        ]
    },
    {
        "id": "ui-message-input",
        "type": "ui_text_input",
        "z": "flow-1",
        "name": "Message Input",
        "label": "Pesan Anda",
        "tooltip": "Ketik pesan dan tekan Enter",
        "group": "chat-group",
        "order": 2,
        "width": 8,
        "height": 1,
        "passthru": false,
        "mode": "text",
        "delay": 0,
        "topic": "chat_input",
        "x": 250,
        "y": 120,
        "wires": [
            ["send-message-function"]
        ]
    },
    {
        "id": "ui-send-button",
        "type": "ui_button",
        "z": "flow-1",
        "name": "Send Button",
        "group": "chat-group",
        "order": 3,
        "width": 2,
        "height": 1,
        "passthru": false,
        "label": "Kirim",
        "tooltip": "",
        "color": "",
        "bgcolor": "",
        "className": "",
        "icon": "",
        "payload": "",
        "payloadType": "str",
        "topic": "chat_input",
        "topicType": "msg",
        "x": 250,
        "y": 160,
        "wires": [
            ["send-message-function"]
        ]
    },
    {
        "id": "ui-chat-display",
        "type": "ui_text",
        "z": "flow-1",
        "group": "chat-group",
        "order": 4,
        "width": 12,
        "height": 10,
        "name": "Chat Display",
        "label": "Percakapan",
        "format": "{{msg.payload}}",
        "className": "chat-messages",
        "x": 650,
        "y": 280,
        "wires": []
    },
    {
        "id": "ui-clear-button",
        "type": "ui_button",
        "z": "flow-1",
        "name": "Clear Chat",
        "group": "chat-group",
        "order": 5,
        "width": 3,
        "height": 1,
        "passthru": false,
        "label": "Clear Chat",
        "tooltip": "",
        "color": "",
        "bgcolor": "red",
        "className": "",
        "icon": "",
        "payload": "",
        "payloadType": "str",
        "topic": "clear_chat",
        "topicType": "msg",
        "x": 250,
        "y": 360,
        "wires": [
            ["clear-chat"]
        ]
    },
    {
        "id": "ui-info",
        "type": "ui_text",
        "z": "flow-1",
        "group": "chat-group",
        "order": 0,
        "width": 12,
        "height": 2,
        "name": "Info",
        "label": "Informasi",
        "format": "<h3>💬 Chat MQTT dengan HiveMQ</h3><p>Broker: broker.hivemq.com:1883 | Topic: chat/room/public</p><p>Set username terlebih dahulu sebelum chat!</p>",
        "className": "info-panel",
        "x": 250,
        "y": 80,
        "wires": []
    },
    {
        "id": "chat-group",
        "type": "ui_group",
        "name": "MQTT Chat Room",
        "tab": "chat-tab",
        "order": 1,
        "disp": true,
        "width": "12",
        "collapse": false,
        "className": ""
    },
    {
        "id": "chat-tab",
        "type": "ui_tab",
        "name": "MQTT Chat",
        "icon": "chat",
        "order": 1,
        "disabled": false,
        "hidden": false
    }
]
